# .github/workflows/deploy.yml
# .github/workflows/deploy.yml
name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  GCP_REGION: asia-south1
  GCP_ARTIFACT_REPO: gokart-server
  GCP_GAR_HOST: asia-south1-docker.pkg.dev

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    strategy:
      matrix:
        service:
          - name: api
            run_service_name: gokart-api
            dockerfile: Dockerfile.api
            paths: |
              cmd/api/**
              internal/**
              configs/**
              events/**
              pkg/**
              go.mod
              go.sum
          - name: mega-worker
            run_service_name: mega-worker
            dockerfile: Dockerfile.mega-worker
            paths: |
              cmd/mega-worker/**
              workers/**
              events/**
              pkg/**
              go.mod
              go.sum

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Get changed files'
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: ${{ matrix.service.paths }}

      - name: Authenticate to Google Cloud
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
          service_account: '${{ secrets.GCP_SA_EMAIL_FOR_ACTIONS }}'

      - name: Set up Docker Buildx
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.service.dockerfile }}
          push: true
          # CORRECTED: Use secrets.GCP_PROJECT_ID here
          tags: ${{ env.GCP_GAR_HOST }}/${{ secrets.GCP_PROJECT_ID }}/${{ env.GCP_ARTIFACT_REPO }}/${{ matrix.service.name }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ matrix.service.run_service_name }}
          region: ${{ env.GCP_REGION }}
          # CORRECTED: Use secrets.GCP_PROJECT_ID here as well
          image: ${{ env.GCP_GAR_HOST }}/${{ secrets.GCP_PROJECT_ID }}/${{ env.GCP_ARTIFACT_REPO }}/${{ matrix.service.name }}:${{ github.sha }}